### ISSUE TITLE
Incorrect instructions on registry

### ISSUE THREAD

**Issue by aguillon** [ligolang/NFT-factory-cameligo#15]
On [the registry page for this package](https://packages.ligolang.org/template/NFT-Factory-Cameligo), the following command line is given to get the template:
```bash
ligo init contract --template nft-factory-cameligo [PROJECT_NAME]
```

However this does not work, as the correct name for the template is `NFT-factory-cameligo`. I did not find where to change this.

**Comment by JulesGuesnon** [comment]
It'll be fix the next release of registry
